import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import MediaCard from '../components/Card'
import { Grid, Box } from '@mui/material'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>buy Sinage-adversise</h1>
        <div>
          <Box >
            <Grid container spacing={2}>
              <Grid item xs={6} sx={{ width: 1 }} justifyContent="center" alignItems="center"><MediaCard nft={{name:"a", description:"desc", image:"/images/wall1.jpg"}}/></Grid>
              <Grid item xs={6} sx={{ width: 1 }} justifyContent="center" alignItems="center"><MediaCard nft={{name:"b", description:"desc", image:"/images/wall2.jpg"}}/></Grid>
            </Grid>
          </Box>
        </div>
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}

export default Home
