import React, { useState } from "react"
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import MediaCard from '../components/Card'
import { Grid, Box, Button } from '@mui/material'
import { ethers } from 'ethers'
import { Sinage_nft__factory } from "../../typechain-types/"
import NFT from '../../artifacts/contracts/Sinage-nft.sol/Sinage_nft.json'

declare var window: any

interface NFT{
  nft: {
      name: string
      description: string
      image: string
  }
}

interface NFT2{
    name: string
    description: string
    image: string
  }




const Home: NextPage = () => {  
  const [imageURL, setImageURL] = useState("/images/wall1.jpg");



const onClick = async () => {
    if (!window.ethereum) {
      console.error('!window.ethereum')
      return
    }
  
    const provider = new ethers.providers.Web3Provider(window.ethereum)
    await provider.send('eth_requestAccounts', [])
    const signer = await provider.getSigner()
    /*
    const Sinage_nft = Sinage_nft__factory.connect(
      "0x5FbDB2315678afecb367f032d93F642f64180aa3",
      signer
    )
    */
    
    console.log(await signer.getAddress());
    const nftContract = new ethers.Contract(
      "0x95f1f1D9B73E51772b61aC612Fefc5d908Af8b8A",
      NFT.abi,
      signer
    )
    console.log(nftContract)
    
    const ret = await nftContract['tokenURI(uint256)'](5)
    console.log(ret)
    const b64result = ret.replace("data:application/json;base64,", "")
    const strResult = Buffer.from(b64result, "base64").toString()
    const jsonResult0 = JSON.parse(strResult);
    console.log(jsonResult0.image);
    setImageURL(jsonResult0.image)
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <div>
            <Image src={imageURL} width={640} height={400}/>
            <Button onClick={onClick} size="small">reload</Button>
        </div>
        
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}

export default Home
